### ISSUE TITLE
error: cannot find symbol method

### ISSUE THREAD

**Issue by zuhairahmad87** [Patchett/CryptoBuddy#14]
error: cannot find symbol method asObservable() |  
-- | --
error: cannot find symbol method asSimpleObservable() |  

com/cryptobuddy/ryanbridges/cryptobuddy/rest/NewsService.java |

**Comment by mudi256** [comment]
same issue

**Comment by ZackPashkin** [comment]
same issue

**Comment by BrijeshChodvadiya** [comment]
solution of this error???

**Comment by Patchett** [comment]
Try pulling master now guys. Hopefully it's fixed with the latest changes
