### ISSUE TITLE
i ca't find ART image in master menu background

### ISSUE THREAD

**Issue by jaxporon** [Patchett/CryptoBuddy#17]
hi and so tanks for this app src 
i cannot fint ART image backgrounf in master menu in main activity 
please help me to find and change it 
tanks

**Comment by Patchett** [comment]
There is no `ART` image background or drawable. I set it up here: https://github.com/Patchett/CryptoBuddy/blob/e79fe0fabbb89066495c8801d28b44f0fbc86da2/app/src/main/java/com/cryptobuddy/ryanbridges/cryptobuddy/currencylist/CurrencyListTabsActivity.java#L77-L98

**Comment by jaxporon** [comment]
fine so tnks i find it 
but i need set image to this location without text ART 
please help me to wite this code

**Comment by Patchett** [comment]
I am using Material Drawer Library to render the drawer: https://github.com/mikepenz/MaterialDrawer

You can read through the documentation at that link to learn how to set an image in the drawer, it should be pretty straight forward
